[package]
name = "voice-labs"
version = "0.1.0"
description = "Local-first speech lab"
authors = ["Philipp Wagner"]
license = "MIT"
edition = "2021"
rust-version = "1.77"

[lib]
name = "voice_labs_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
